site_name: SettingsFramework Documentation
site_description: Documentation for the UE5 SettingsFramework Plugin

theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
  palette:
    scheme: slate

plugins:
  - search
  - mkdoxy:
      projects:
        SettingsFramework:
          src-dirs: "Source/SettingsFramework/Public Source/SettingsFramework/Private"
          full-doc: True
          doxy-cfg:
            PROJECT_NAME: "SettingsFramework"
            GENERATE_HTML: NO
            GENERATE_XML: YES
            FILE_PATTERNS: "*.cpp *.h"
            FORCE_LOCAL_INCLUDES: YES
            STRIP_FROM_INC_PATH: "Source/SettingsFramework/Public"
            RECURSIVE: YES
            EXTRACT_ALL: YES
            SORT_MEMBER_DOCS: NO
            SORT_BRIEF_DOCS: NO
            ENABLE_PREPROCESSING: YES
            MACRO_EXPANSION: YES
            EXPAND_ONLY_PREDEF: YES
            PREDEFINED: >
              "UCLASS(...)= "
              "USTRUCT(...)= "
              "UENUM(...)= "
              "GENERATED_BODY()= "
              "UPROPERTY(...)= "
              "UFUNCTION(...)= "
              "PURE_VIRTUAL(...)="
            ALIASES: >
              bc="<kbd>BlueprintCallable</kbd>"
              bp="<kbd>BlueprintPure</kbd>"
              bne="<kbd>BlueprintNativeEvent</kbd>"
              bie="<kbd>BlueprintImplementableEvent</kbd>"
              edo="<kbd>EditDefaultsOnly</kbd>"
              ea="<kbd>EditAnywhere</kbd>"
              brw="<kbd>BlueprintReadWrite</kbd>"
              bro="<kbd>BlueprintReadOnly</kbd>"
              i="<kbd>Instanced</kbd>"
              va="<kbd>VisibleAnywhere</kbd>"

nav:
  - Home: index.md 
  - Installation: installation.md
  - Blueprint Guide: blueprint.md
  - API Reference: api.md