site_name: SettingsFramework Documentation
site_description: Documentation for the UE5 SettingsFramework Plugin

theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
  palette:
    scheme: slate

plugins:
  - search
  - mkdoxy:
      projects:
        SettingsFramework:
          src-dirs: "Source/SettingsFramework/Public Source/SettingsFramework/Private"
          full-doc: True
          doxy-cfg:
            PROJECT_NAME: "SettingsFramework"
            GENERATE_HTML: NO
            GENERATE_XML: YES
            FILE_PATTERNS: "*.cpp *.h"
            RECURSIVE: YES
            EXTRACT_ALL: YES
            ENABLE_PREPROCESSING: YES
            MACRO_EXPANSION: YES
            EXPAND_ONLY_PREDEF: YES
            PREDEFINED: >
              "UCLASS(...)= "
              "USTRUCT(...)= "
              "UENUM(...)= "
              "GENERATED_BODY()= "
              "UPROPERTY(...)= "
              "UFUNCTION(...)= "
              "PURE_VIRTUAL(...)="

nav:
  - Home: index.md 
  - Installation: installation.md
  - Blueprint Guide: blueprint.md
  - API Reference: api.md