name: Deploy Documentation
on:
  push:
    branches:
      - main
      - documentation
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      
      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen
      
      - name: Install Python dependencies
        run: |
          pip install mkdocs-material
          pip install mkdoxy
      
      - name: Deploy Docs to Github Pages
        run: mkdocs gh-deploy --force